[project]
name = "fraise-sdk"
version = "0.2.0-alpha.0"
description = "Fraise SDK"
authors = [
    { name = "Rene Jean Corneille", email = "14303619+RonsenbergVI@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.33.1",
]

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
anthropic = [
    "claude-agent-sdk>=0.2.128",
]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.0.0",
]
openai = [
    "openai-agents>=0.18.3",
]
